sudo: false
language: cpp

compiler:
  - gcc
  - clang

#before_install:
  #  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

install:
  - cmake .

script:
  - make

notifications:
  irc:
    channels:
      - "irc.oftc.net#freerct"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch} - %{commit} - %{author}: %{message}"
      - "Build #%{build_number} - Details: %{build_url}"
    use_notice: true
    skip_join: true

env:
  global:
    secure: "gUgAXzGLyEkqSuMav5PLylFL3vtDO+TetIqzivkWDP5G6Md2W4xCSxBtgORtgOSngfJFipnoSvIzRo85ZyOJXKxN+1Ayy4D+xanFHpfY5pZtdhrpd9nbUXM/XLTJ9KeCd7n8BUq3Qd1h6cEAfCwvajSavC+bll3Df3MfSxISLdI="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - ubuntu-precise
    packages:
      - build-essential
      - cmake
      - gcc-4.8
      - g++-4.8
      - clang
      - bison
      - flex
      - libpng-dev
      - libsdl2-dev
      - libsdl2-ttf-dev
  coverity_scan:
    project:
      name: "FreeRCT/FreeRCT"
      description: "Build from Travis-CI"
    build_command_prepend: "cmake ."
    build_command: "make"
    notification_email: freerct@gmail.com
    branch_pattern: coverity
